version: '3.3'

services:
  server:
    image: ${BUILD_IMAGE}
    environment:
      TEST_RESULTS_DIR: ${TEST_RESULTS_DIR}
    volumes:
      - .:/home/application
    command: ["/home/application/run-tests-ci.sh"]
    user: root
    depends_on:
      - stubby4j

  stubby4j:
    image: sandokandias/stubby4j-docker
    environment:
      STUBBY_PORT: 8882
    volumes:
      - ./testdata/stubby4j/integrations.yml:/usr/local/stubby.yml
      - ./testdata/stubby4j/response.zip:/usr/local/response.zip
