version: 2.1

orbs:
  win: circleci/windows@2.2.0

references:
  images:
    go: &GOLANG_IMAGE cimg/go:1.14
    python: &PYTHON_IMAGE circleci/python:2.7-stretch
    ruby: &RUBY_IMAGE cimg/ruby:2.6.5
    horus: &HORUS_IMAGE library/docker:dind
    ubuntu: &UBUNTU_IMAGE cimg/base:2020.01
    centos: &CENTOS_IMAGE viniciusramosdefaria/centos-circleci:7.0
    windows: &WINDOWS_IMAGE win/default

  paths:
    test-results: &TEST_RESULTS_DIR bin

  environment: &ENVIRONMENT
    TEST_RESULTS_DIR: *TEST_RESULTS_DIR
    GIT_EMAIL : "zup-ci@zup.com.br"
    GIT_USERNAME: "zup-ci"
    GIT_NAME: "Zup CI"

  filters: &FILTERS_DELIVERY
    branches:
      only:
        - /^release-.*/
        - qa
        - nightly
        - beta
        - feature/packaging

  filters-release: &FILTERS_RELEASE
    branches:
      only:
        - /^release-.*/

  filters-checks: &FILTERS_CHECK
    branches:
      only:
        - master
        - /^release-.*/
        - nightly
        - beta
        - feature/packaging

  filters-checks-pr: &FILTERS_CHECK_CODE
    branches:
      only:
        - qa
        - /^pull\/.*$/

executors:
  ritchie-executor:
    docker:
      - image: *GOLANG_IMAGE
        user: root
    working_directory: /workspace

  horus-executor:
    docker:
      - image: *HORUS_IMAGE
        user: root

  delivery-executor:
    docker:
      - image: *PYTHON_IMAGE
        user: root
    working_directory: /workspace

  release-executor:
    docker:
      - image: *RUBY_IMAGE
        user: root
    working_directory: /workspace

  ubuntu-executor:
    docker:
      - image: *UBUNTU_IMAGE
        user: root
    working_directory: /workspace

  centos-executor:
    docker:
      - image: *CENTOS_IMAGE
        user: root
    working_directory: /workspace

  windows-executor:
    docker:
      - image: *WINDOWS_IMAGE
        user: root
    working_directory: /workspace

jobs:
  lint:
    executor: ritchie-executor
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            download=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
            wget -O- -q $download | sh -s -- -b /go/bin/ v1.24.0
      - run:
          name: lint
          command: |
            go mod download
            /go/bin/golangci-lint run

  horus:
    executor: horus-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - setup_remote_docker
      - run:
          name: Horus Security Analysis
          command: |
            echo "Starting scan Horus..."
            docker run --rm -e HORUS_CLIENT_REPO_URL=$HORUS_CLIENT_REPO_URL \
            -e HORUS_CLIENT_REPO_BRANCH=$HORUS_CLIENT_REPO_BRANCH \
            -e HORUS_CLIENT_API_ADDR=$HORUS_CLIENT_API_ADDR \
            -e HORUS_CLIENT_TOKEN=$HORUS_CLIENT_TOKEN \
            -e HORUS_CLIENT_API_USE_HTTPS=$HORUS_CLIENT_API_USE_HTTPS \
            -e HORUS_VULNERABILITY_CHECK=$HORUS_VULNERABILITY_CHECK horuszup/horus-client:latest

  unit_test:
    executor: ritchie-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Running Unit tests
          command: |
            mkdir -p $TEST_RESULTS_DIR
            go mod download
            PACKAGE_NAMES=$(go list ./pkg/... | circleci tests split --split-by=timings --timings-type=classname)
            echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
            echo $PACKAGE_NAMES
            gotestsum --format=short-verbose \
              --junitfile $TEST_RESULTS_DIR/gotestsum-report.xml -- \
              -p 2 \
              -cover -coverprofile=coverage.txt \
              $PACKAGE_NAMES
      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR
      - run:
          name: codecov upload
          when: always
          command: bash <(curl -s https://codecov.io/bash)

  functional_test_single:
    executor: ritchie-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - attach_workspace:
            at: /workspace/dist
      - run:
          name: Setup Bash for Single
          command: |
            echo "export PATH=/workspace/dist/linux/single:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Running Functional tests for single
          command: |
            go mod download
            make functional-test-single

  functional_test_team:
    executor: ritchie-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Setup Bash for Team
          command: |
            echo "export PATH=/workspace/dist/linux/team:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Running Functional tests for team
          command: |
            go mod download
            make functional-test-team

  build:
    executor: ritchie-executor
    branches:
    steps:
      - checkout
      - run:
          name: Running build
          command: |
            . ./.circleci/scripts/version.sh
            go mod download
            make build-circle
      - persist_to_workspace:
          root: dist
          paths:
            - linux
            - darwin
            - windows
      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR

  delivery:
    executor: delivery-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Delivering cli binary
          command: |
            pip install awscli
            . ./.circleci/scripts/version.sh
            . ./.circleci/scripts/bucket.sh
            . ./.circleci/scripts/credentials.sh
            make delivery

  deb-package:
    environment:
      <<: *ENVIRONMENT
    executor: ubuntu-executor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Generating package for debian
          command: |
            . ./.circleci/scripts/version.sh
            . ./.circleci/scripts/gen-deb.sh
      - store_artifacts:
          path: *TEST_RESULTS_DIR

  rpm-package:
    environment:
      <<: *ENVIRONMENT
    executor: centos-executor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Generating package for rpm
          command: |
            . ./.circleci/scripts/version.sh
            . ./.circleci/scripts/gen-rpm.sh
      - store_artifacts:
          path: *TEST_RESULTS_DIR


  win-package:
    executor:
      name: win/default
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          command: |
            . ./.circleci/scripts/version.sh
            echo $RELEASE_VERSION > release_version.txt
          shell: bash.exe
      - run:
          command: |
            .circleci/scripts/gen-win.ps1
          shell: powershell.exe
      - persist_to_workspace:
          root: dist
          paths:
            - installer

  release:
    environment:
      <<: *ENVIRONMENT
    executor: release-executor
    steps:
      - checkout
      - run:
          name: Releasing
          command: |
            . ./.circleci/scripts/version.sh
            make release

  rebase_nightly:
    environment:
      <<: *ENVIRONMENT
    executor: release-executor
    steps:
      - checkout
      - run:
          name: Rebase Nightly
          command: |
            make rebase-nightly

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - rebase_nightly

  build-for-branch:
    jobs:
#      - lint:
#          filters:
#            <<: *FILTERS_CHECK_CODE
#      - horus:
#          filters:
#            <<: *FILTERS_CHECK_CODE
#          requires:
#            - lint
#      - unit_test:
#         name: unit-test
#         filters:
#           <<: *FILTERS_CHECK_CODE
#         requires:
#           - horus
#      - build:
#          name: build-code
#          filters:
#            <<: *FILTERS_CHECK_CODE
#          requires:
#            - unit-test
#      - functional_test_single:
#          name: functional_test_single_code
#          filters:
#            <<: *FILTERS_CHECK_CODE
#          requires:
#            - build-code
#      - functional_test_team:
#          name: functional_test_team_code
#          filters:
#            <<: *FILTERS_CHECK_CODE
#          requires:
#            - build-code
#      - unit_test:
#          name: unit-tests
#          filters:
#            <<: *FILTERS_CHECK
      - build:
          filters:
            <<: *FILTERS_CHECK
#          requires:
#            - unit-tests
#      - functional_test_single:
#          filters:
#            <<: *FILTERS_CHECK
#          requires:
#            - build
#      - functional_test_team:
#          filters:
#            <<: *FILTERS_CHECK
#          requires:
#            - build
      - delivery:
          filters:
            <<: *FILTERS_DELIVERY
          requires:
            - deb-package
            - rpm-package
            - win-package
#            - functional_test_single
#            - functional_test_team
#      - release:
#          filters:
#            <<: *FILTERS_RELEASE
#          requires:
#            - delivery
      - deb-package:
          filters:
            <<: *FILTERS_CHECK
          requires:
            - build
      - rpm-package:
          filters:
            <<: *FILTERS_CHECK
          requires:
            - build
      - win-package:
          filters:
            <<: *FILTERS_CHECK
          requires:
            - build