# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs

jobs:
  builder:
    docker:
      - image: golang:1.13-alpine
    steps:
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            echo "7224aa97-1f94-4679-917d-9c7bb10074ab" > /etc/machine-id
            apk update && apk add \
                alpine-sdk \
                gettext \
                curl \
                python \
                py-pip \
                jq \
                git \
                && pip install --no-cache-dir awscli==1.16.310 \
                && apk del py-pip \
                && rm -rf /var/cache/apk/* /root/.cache/pip/* /usr/lib/python2.7/site-packages/awscli/examples
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
  test:
    docker:
      - image: golang:1.13-alpine
    steps:
      - checkout
      - run:
          name: Running test
          command: make test
  build:
    docker:
      - image: golang:1.13-alpine
    steps:
      - checkout
      - run:
          name: Running build
          command: make build

workflows:
  build_and_test:
    jobs:
      - test:
          requires:
            - builder
      - build:
          requires:
            - test
