# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  ritchie-executor:
    docker:
      - image: circleci/golang:1.14.1
        user: root
    working_directory: /workspace

jobs:

  test:
    executor: ritchie-executor
    steps:
      - checkout
      - run:
          name: Running test
          command: |
            echo "7224aa97-1f94-4679-917d-9c7bb10074ab" > /etc/machine-id
            make test

  build:
    executor: ritchie-executor
    steps:
      - checkout
      - run:
          name: Running build
          command: |
            make build
            ls dist
      - persist_to_workspace:
          root: dist
          paths:
            - linux
            - darwin
            - windows

  delivery:
    executor: ritchie-executor
    steps:
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Running build
          command: |
            ls

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
      - delivery:
          requires:
            - build