version: 2.1

references:
  images:
    go: &GOLANG_IMAGE cimg/go:1.14
    python: &PYTHON_IMAGE circleci/python:2.7-stretch

  environment: &ENVIRONMENT
    S3_ARTIFACT_BUCKET: ritchie-cli-bucket152849730126474

  filters: &FILTERS
    branches:
      only:
        - master
        - circleci-project-setup

executors:
  ritchie-executor:
    docker:
      - image: *GOLANG_IMAGE
        user: root
    working_directory: /workspace

  delivery-executor:
    docker:
      - image: *PYTHON_IMAGE
        user: root
    working_directory: /workspace

jobs:

  test:
    executor: ritchie-executor
    steps:
      - checkout
      - run:
          name: Running test
          command: |
            echo "7224aa97-1f94-4679-917d-9c7bb10074ab" > /etc/machine-id
            make test

  build:
    executor: ritchie-executor
    branches:
    steps:
      - checkout
      - run:
          name: Running build
          command: |
            make build
      - persist_to_workspace:
          root: dist
          paths:
            - linux
            - darwin
            - windows

  delivery:
    executor: delivery-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Running build
          command: |
            pip install awscli
            make toto

workflows:
  build_and_test:
    jobs:
      - test:
          filters:
            <<: *FILTERS
      - build:
          filters:
            <<: *FILTERS
          requires:
            - test
      - delivery:
          filters:
            <<: *FILTERS
          requires:
            - build