# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: opensimsim/aws-cli@1.2.0

executors:
  ritchie-executor:
    docker:
      - image: cimg/go:1.14
        user: root
    working_directory: /workspace

  delivery-executor:
    docker:
      - image: circleci/python:2.7-stretch
        user: root
    working_directory: /workspace

jobs:

  test:
    executor: ritchie-executor
    steps:
      - checkout
      - run:
          name: Running test
          command: |
            echo "7224aa97-1f94-4679-917d-9c7bb10074ab" > /etc/machine-id
            make test

  build:
    executor: ritchie-executor
    steps:
      - checkout
      - run:
          name: Running build
          command: |
            make build
      - persist_to_workspace:
          root: dist
          paths:
            - linux
            - darwin
            - windows

  delivery:
    executor: delivery-executor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace/dist
      - run:
          name: Running build
          command: |
            pip install awscli
            AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} make toto

workflows:
  build_and_test:
    jobs:
#      - test
#      - build:
#          requires:
#            - test
      - delivery
#          requires:
#            - build